services:
  frontend:
    build:
      context: frontend
    container_name: hngfrontend-task
    image: xenacod/hngfrontend-task
    ports:
      - "3000:3000"
  api:
    build:
      context: api
    container_name: hngbackend-task
    image:  xenacod/hngbackend-task
    ports:
      - "9000:9000"